<?php  if ( ! defined('CONFIG')) exit('No direct script access allowed');

// This file maps the channel number to the file name
// of the icon including extension.
//
// Note that the channel icons must reside in
// public/images/channel_icons/

$icon = array(	'4' => 'cbs.png',
		'433' => 'cbs.png',
		'804' => 'cbs.png',
		'2' => 'pbs.png',
		'202' => 'pbs.png',
		'440' => 'pbs.png',
		'802' => 'pbs.png',
		'13' => 'pbs.png',
		'80' => 'pbs.png',
		'5' => 'abc.png',
		'206' => 'abc.png',
		'431' => 'abc.png',
		'805' => 'abc.png',
		'11' => 'nbc.png',
		'216' => 'nbc.png',
		'432' => 'nbc.png',
		'811' => 'nbc.png',
		'7' => 'tbs.png',
		'36' => 'tbs.png',
		'407' => 'tbs.png',
		'879' => 'tbs.png',
		'442' => 'tbs.png',
		'826' => 'tbs.png',
		'8' => 'cw.png',
		'211' => 'cw.png',
		'435' => 'cw.png',
		'808' => 'cw.png',
		'10' => 'mytv.png',
		'220' => 'mytv.png',
		'436' => 'mytv.png',
		'807' => 'mytv.png',
		'9' => 'fox.png',
		'434' => 'fox.png',
		'809' => 'fox.png',
		'22' => 'wgn.png',
		'810' => 'wgn.png',
		'12' => 'kstc.png',
		'208' => 'kstc.png',
		'209' => 'kstc.png',
		'214' => 'kstc.png',
		'439' => 'kstc.png',
		'812' => 'kstc.png');
